# Generated by Django 5.2.8 on 2025-11-15 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GamePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('steam', 'Steam'), ('epic', 'Epic Games Store'), ('ubisoft', 'Ubisoft Store'), ('xbox', 'Xbox Store'), ('gog', 'GOG'), ('ea', 'EA Store'), ('playstation', 'PlayStation Store'), ('nintendo', 'Nintendo eShop')], db_index=True, max_length=30)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_percent', models.IntegerField(default=0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='tracker.game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('steam', 'Steam'), ('epic', 'Epic Games Store'), ('ubisoft', 'Ubisoft Store'), ('xbox', 'Xbox Store'), ('gog', 'GOG'), ('ea', 'EA Store'), ('playstation', 'PlayStation Store'), ('nintendo', 'Nintendo eShop')], db_index=True, max_length=30)),
                ('platform_game_id', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='tracker.game')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'platform'), name='unique_game_platform')],
            },
        ),
        migrations.CreateModel(
            name='GamePriceCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('steam', 'Steam'), ('epic', 'Epic Games Store'), ('ubisoft', 'Ubisoft Store'), ('xbox', 'Xbox Store'), ('gog', 'GOG'), ('ea', 'EA Store'), ('playstation', 'PlayStation Store'), ('nintendo', 'Nintendo eShop')], db_index=True, max_length=30)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_percent', models.IntegerField(default=0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_price', to='tracker.game')),
            ],
            options={
                'ordering': ['game__title', 'platform'],
                'constraints': [models.UniqueConstraint(fields=('game', 'platform'), name='unique_game_platform_pricecurrent')],
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'game'), name='unique_user_game_wishlist')],
            },
        ),
    ]
